Try set +e in bash script for pytest runs.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -71,28 +71,39 @@ jobs:
         run: |
           ls -l "$(python -c 'import csparse; print(csparse.__path__[0])')"
 
-      - name: Run Python Unit Tests
+      - name: Run Python unit tests with conditional reruns
         # TODO pytest --make-figures
         # pytest --last-failed (re-run with only the last failed tests)
         # env:
         #   MPLBACKEND: agg  # use headless backend for matplotlib
-        continue-on-error: true
-        id: pytest_full_run
-        run: pytest
-
-      - name: Check for pytest run outcome
-        if: steps.pytest_full_run.outcome == 'failure'
         run: |
-          echo "::warning::Pytest run may have segfaulted."
-          echo "--- Re-running pytest, but skipping TestLU."
+          #!/bin/bash
+          # Allow script to continue on error
+          set +e
+
+          # Run pytest in a subshell in case it segfaults
+          echo "--- Running pytest with full test suite."
+          (pytest)
+          INITIAL_EXIT_CODE=$?
+
+          echo "--- Initial pytest exit code $INITIAL_EXIT_CODE."
+
+          # Check if the initial pytest run failed
           DESELECT_TESTS='--deselect=python/csparse/tests/test_lu.py::TestLU'
+          LAST_FAILED_FLAGS='-v -s --last-failed --tb=auto --showlocals'
 
-          pytest $DESELECT_TESTS
-
-          if [[ $? -ne 0 ]]; then
-              echo "--- Re-run failed, running with last-failed option."
-              LAST_FAILED_FLAGS='-v -s --last-failed --tb=auto --showlocals'
-              pytest $DESELECT_TESTS $LAST_FAILED_FLAGS
+          if [[ $INITIAL_EXIT_CODE -eq 139 ]]; then
+              echo "--- Initial pytest run likely segfaulted (exit code 139)."
+              echo "--- Re-Run: skipping TestLU."
+              pytest $DESELECT_TESTS
+              if [[ $? -ne 0 ]]; then
+                  echo "--- Re-run: pytest still failed after skipping TestLU."
+                  pytest $DESELECT_TESTS $LAST_FAILED_FLAGS
+              fi
+          elif [[ $INITIAL_EXIT_CODE -ne 0 ]]; then
+              echo "--- Initial pytest failed: exit code $INITIAL_EXIT_CODE."
+              echo "--- Re-run: last failed tests."
+              pytest $LAST_FAILED_FLAGS
           fi
 
       - name: Build C++ Demos
